import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import NftBox from "../components/NftBox";

const NFTs = [
  {
    tokenId: "001",
    nftAddress: "0x9819cE0bA8508aC315B95e5baA4FA8C3152E5F80",
    price: "0.01",
    name: "Raskutty",
    symbol: "RAS",
    owner: "0x014EC6296B3493f0f59a3FE90E0FFf377fb8826a",
    image:
      "https://ipfs.io/ipfs/QmZnScwT4ehSo96KHaAvXoRe9iiE31no2DBPibNmCaBT6a?filename=Io.jpeg",
    metadata:
      "https://ipfs.io/ipfs/QmUivNqDWwwcHavYFQaSzWWkTqoBkzDbQ5UhAPUv5yQNHd?filename=basicUri.json",
  },
  {
    tokenId: "002",
    nftAddress: "0x9819cE0bA8508aC315B95e5baA4FA8C3152E5F80",
    price: "0.01",
    name: "Raskutty",
    symbol: "RAS",
    owner: "0x014EC6296B3493f0f59a3FE90E0FFf377fb8826a",
    image:
      "https://ipfs.io/ipfs/QmZnScwT4ehSo96KHaAvXoRe9iiE31no2DBPibNmCaBT6a?filename=Io.jpeg",
    metadata:
      "https://ipfs.io/ipfs/QmUivNqDWwwcHavYFQaSzWWkTqoBkzDbQ5UhAPUv5yQNHd?filename=basicUri.json",
  },
  {
    tokenId: "003",
    nftAddress: "0x9819cE0bA8508aC315B95e5baA4FA8C3152E5F80",
    price: "0.01",
    name: "Raskutty",
    symbol: "RAS",
    owner: "0x014EC6296B3493f0f59a3FE90E0FFf377fb8826a",
    image:
      "https://ipfs.io/ipfs/QmZnScwT4ehSo96KHaAvXoRe9iiE31no2DBPibNmCaBT6a?filename=Io.jpeg",
    metadata:
      "https://ipfs.io/ipfs/QmUivNqDWwwcHavYFQaSzWWkTqoBkzDbQ5UhAPUv5yQNHd?filename=basicUri.json",
  },
];

export default function Home() {
  return (
    <div className="px-8 overflow-scroll">
      <Head>
        <title>Decentralised NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mt-10 grid gap-10 overflow-scroll sm:grid sm:grid-cols-4 sm:justify-center sm:align-center sm:gap-2">
        {NFTs.map((nft) => {
          return <NftBox {...nft} />;
        })}
      </div>
    </div>
  );
}
