import Head from "next/head";
import Header from "../components/Header";
import NftBox from "../components/NftBox";
import { useQuery } from "@apollo/client";
import DUMMY_NFTS from "../constants/dummyNfts";
import GET_ACTIVE_ITEMS from "../constants/graphQueries";
import { useMoralis } from "react-moralis";
import contractAddresses from "../constants/contractAddresses.json";

export default function Home() {
  // querying the active items
  const { loading, data: listedItems } = useQuery(GET_ACTIVE_ITEMS);

  const { chainId } = useMoralis();
  const chainIdString = chainId ? parseInt(chainId).toString() : "31337";

  const nftMarketplaceAddress =
    contractAddresses[chainIdString].nftMarketplace[0];

  return loading || !listedItems ? (
    <p>Loadind....</p>
  ) : (
    <div className="px-8 overflow-scroll max-h-sm">
      <Head>
        <title>Decentralised NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="mt-10 grid gap-10 overflow-scroll sm:grid sm:grid-cols-4 sm:justify-center sm:align-center sm:gap-2">
        {listedItems.activeItems.map((nft) => {
          return (
            <NftBox
              owner={nft.seller}
              nftAddress={nft.nftAddress}
              tokenId={+nft.tokenId}
              price={nft.price}
              marketplace={nftMarketplaceAddress}
              key={`${nft.tokenId}${nft.nftAddress}`}
            />
          );
        })}
      </div>
    </div>
  );
}
