import Head from "next/head";
import Header from "../components/Header";
import basicNftAbi from "../constants/BasicNft.json";
import { useMoralis, useWeb3Contract } from "react-moralis";
import contractAddresses from "../constants/contractAddresses.json";
import { useEffect, useState } from "react";

const nftAddress = "0x9819cE0bA8508aC315B95e5baA4FA8C3152E5F80";

export default function Home() {
  const { isWeb3Enabled } = useMoralis();
  const [tokenURI, setTokenURI] = useState("");
  const { runContractFunction: getTokenURI } = useWeb3Contract({
    abi: basicNftAbi,
    contractAddress: nftAddress,
    functionName: "getTokenURI",
    params: {
      tokenId: 1,
    },
  });

  async function update() {
    const response = await getTokenURI();
    console.log(response);
    setTokenURI(response);
  }

  useEffect(() => {
    if (isWeb3Enabled) {
      (async () => await update())();
      //   update();
    }
  }, [isWeb3Enabled]);
  return (
    <div className="px-8 overflow-scroll max-h-sm">
      <Head>
        <title>token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p>Token</p>
      <p>{tokenURI}</p>
    </div>
  );
}
